#!/bin/sh

set -e

#mysql -u ocara -p12345678 -e "DROP DATABASE ocara;"

rm -vfR /usr/lib/OcaraServer

# Automatically added by dh_gconf
if [ "$1" = purge ]; then
	OLD_DIR=/etc/gconf/schemas
	SCHEMA_FILES="ocara-server.schemas "
	if [ -d $OLD_DIR ]; then
		for SCHEMA in $SCHEMA_FILES; do
			rm -f $OLD_DIR/$SCHEMA
		done
		rmdir -p --ignore-fail-on-non-empty $OLD_DIR
	fi
fi
# End automatically added section
# Automatically added by dh_gconf
if [ "$1" = purge ]; then
	OLD_DIR=/etc/gconf/schemas
	SCHEMA_FILES="ocara-client.schemas "
	if [ -d $OLD_DIR ]; then
		for SCHEMA in $SCHEMA_FILES; do
			rm -f $OLD_DIR/$SCHEMA
		done
		rmdir -p --ignore-fail-on-non-empty $OLD_DIR
	fi
fi
# End automatically added section
# Automatically added by dh_installmenu
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section
