#!/bin/sh
set -e
# Automatically added by dh_gconf
if [ "$1" = remove ] || [ "$1" = upgrade ]; then
	gconf-schemas --unregister ocara-server.schemas 
fi
# End automatically added section
# Automatically added by dh_gconf
if [ "$1" = remove ] || [ "$1" = upgrade ]; then
	gconf-schemas --unregister ocara-client.schemas 
fi
# End automatically added section
